### ISSUE TITLE
can't remove someone as an admin?

### ISSUE THREAD

**Issue by Kedersha** [OpenSourceFieldlinguistics/FieldDB#1500]
I wanted to see what a read-only corpus would look like, so as elisedemo, I tried to remove elisekm from my corpus as an admin, a reader, and a writer. I wasn't able to remove elisekm as an admin, though, and when I logged in as elisekm I still had all the same privileges as I had before.

**Comment by cesine** [comment]
the new auth api doesnt use tobins functions anymore, so this issue is "fixed"
