### ISSUE TITLE
Cant reset password for psycholing server code users using app and apdev and localhost

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#1565]
XMLHttpRequest cannot load https://auth.example.org/changepassword. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://appdev.example.org' is therefore not allowed access. The response had HTTP status code 401.

**Comment by cesine** [comment]
i thin kthis works, im pretty sure its not an issue anymore

**Comment by hisakonog** [comment]
changed my phophlo user passward in lingsync, it worked.
