### ISSUE TITLE
select boxes arent clickable in sikuli

### ISSUE THREAD

**Issue by farahabbasi** [OpenSourceFieldlinguistics/FieldDB#1736]
none of these are seen by sikuli 

![screen shot 2014-11-23 at 2 45 08 pm](https://cloud.githubusercontent.com/assets/9871077/5159005/ebec0214-7321-11e4-94b1-7b4c846921b6.png)
![screen shot 2014-11-23 at 2 48 58 pm](https://cloud.githubusercontent.com/assets/9871077/5159006/ebec6c5e-7321-11e4-88c7-9813b04c5b0b.png)

**Comment by cesine** [comment]
our workaround was to make it choose hte most recent session by default so we dont have ot create new sessions each test #1803
