### ISSUE TITLE
deploy spreadsheet app for spring field methods session 

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#1822]
the testing app seems ready enough for deployment to all users. 

the last release of the spreadsheet app was on May 5 2014 (1 year ago)

**Comment by cesine** [comment]
done. @hisakonog the spreadhseet app is now deployed, richard and hsi students have been using the upcoming release for abotu 1 week, and so far it seems stable enough to release to all users. we have a backup of the previous relase from last may if we choose to revert.

**Comment by hisakonog** [comment]
@cesine thanks, I think the new release is stable in Chrome. However, the audio doesn't work as it supposed to in Safari (I haven't tested Firefox yet). Do you know if anyone in Richard's class is using browser's other than Chrome? 
Alan told me that Michael Diercks is considering using LingSync for his class this semester (seems like he is back on board!). And maybe Peter Jenks (I think) in Berkeley. Now that the new release is much more customizable, I don't think we need to create a special URL for each field methods class, but should we (maybe it is easier for the user studies purpose)? Should we send the hello instructors email to them as well?

**Comment by cesine** [comment]
last year richards group didnt use the audio. but can you add an issue for the audio in safari? so we can decide when to fix it. we do have a sikuli test that passes in both chrome and firefox... i htink. the commits dont say that i tested it on chrome and firefox so maybe i didnt
https://github.com/OpenSourceFieldlinguistics/fielddb-spreadsheet-sikuli/commits/master/create-datum.sikuli/create-datum.py

I think we should still make URLs for the classes so they have their own release schedule for the app. I'll prepare the urls, and a draft of the welcome email.
