### ISSUE TITLE
Fieldmethods emails for Spring 2015

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#1827]
from #1822 although we dont need custom templates anymore, we should still make URLs for the classes so they have their own release schedule for the app.
  - [ ] prepare the urls, and
  - [ ]  a draft of the welcome email.

**Comment by cesine** [comment]
yes, lets remove 4 and maybe replace it with instructions saying they need to maybe watch the video showing how to customize the fields of their corpus. its in here #1813 (or maybe you could make a new video?)

**Comment by cesine** [comment]
@hisakonog  can you mail this out? i think most instructors have started using the app

**Comment by hisakonog** [comment]
@cesine I added the link to the video in #1813. The schools that might be using LingSync for field methods are Pomona and Berkeley. Could you make partitions for the two schools?

**Comment by cesine** [comment]
okay, they are ready: 
* http://berkeley.lingsync.org/
* http://pomona.lingsync.org/

**Comment by cesine** [comment]
for #1813 i remember you made a new video no? do you want us to upload it or can you upload it to youtube?

**Comment by hisakonog** [comment]
@cesine, thanks no I didn't make a new video, the video tutorial is linked to the youtube video you had already made.

**Comment by hisakonog** [comment]
Sent. Closing this.

**Comment by cesine** [comment]
it turns out reed has been using the app for over a month! we really really should have something easy to find for the field methods instructors so they can self-serve information, rather than us figuring out htey are using the app and sending them an email after all the students have gotten used to the main app url :(

![screen shot 2015-02-26 at 10 01 32 am](https://cloud.githubusercontent.com/assets/196199/6385598/a76687e6-bd9e-11e4-867c-ecca1e8e70cb.png)
