### ISSUE TITLE
Upload slides from LSA workshop

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#1828]
@jrwdunham  can you upload (or basically link here) the slides for the LSA workshop

**Comment by jrwdunham** [comment]
# Slides (.pdf)

* http://jrwdunham.com/files/lsa-lingsync-tutorial-1-what-why.pdf
* http://jrwdunham.com/files/lsa-lingsync-tutorial-2-how.pdf
* http://jrwdunham.com/files/lsa-lingsync-tutorial-3-hands-on.pdf
* http://jrwdunham.com/files/lsa-lingsync-tutorial-4-in-development.pdf

# Screencasts

## .ogv

* http://jrwdunham.com/files/lsa-lingsync-tutorial-1-what-why.ogv
* http://jrwdunham.com/files/lsa-lingsync-tutorial-2-how.ogv
* http://jrwdunham.com/files/lsa-lingsync-tutorial-3-hands-on.ogv
* http://jrwdunham.com/files/lsa-lingsync-tutorial-4-in-development.ogv

## .m4v

* http://jrwdunham.com/files/lsa-lingsync-tutorial-1-what-why.m4v
* http://jrwdunham.com/files/lsa-lingsync-tutorial-2-how.m4v
* http://jrwdunham.com/files/lsa-lingsync-tutorial-3-hands-on.m4v
* http://jrwdunham.com/files/lsa-lingsync-tutorial-4-in-development.m4v

**Comment by cesine** [comment]
awesome! any chance you will put some of it on youtube so we can post it on facebook? or we can put itin the lingsync youtube account...

**Comment by jrwdunham** [comment]
I can put them on facebook or we can do it via the lingsync youtube account. Both work for me. Do you have a preference?

**Comment by cesine** [comment]
your youtube is prefered, then you post them in facebook :)

**Comment by jrwdunham** [comment]
https://www.youtube.com/watch?v=eYThTB9gB0o
https://www.youtube.com/watch?v=R8VmRx6UcCU
https://www.youtube.com/watch?v=gKAHmomPAQc
https://www.youtube.com/watch?v=85XZS_feHBE

**Comment by jrwdunham** [comment]
Screencasts of slides posted above and on the LingSync Facebook page.
