### ISSUE TITLE
Safari doesnt request access to the microphone

### ISSUE THREAD

**Issue by hisakonog** [OpenSourceFieldlinguistics/FieldDB#1830]
the boxes with icons (record, stop, upload) don't show up when clicking the microphone icon. 
before clicking 
![beforeclickaudio](https://cloud.githubusercontent.com/assets/760694/5825484/98428f6e-a0b9-11e4-9567-e4d2dc28ee88.png)

(when you click the microphone icon for the FIRST time after you login and open a corpus, the microphone icon is not crossed. Once you clicked the mic icon, the icon on other datums show up crossed. the screenshot above is 2nd or 3rd datums I tried with recording, that is why the mic icon is already crossed.)

after clicking 
![afterclickaudio](https://cloud.githubusercontent.com/assets/760694/5825486/9d79d94c-a0b9-11e4-9d91-80c763813037.png)

Also the audio player doesn't show up unless there is an audio file already attached (which I actually like).

**Comment by hisakonog** [comment]
audio upload (.mp3, .wav) works fine

**Comment by cesine** [comment]
* it looks like its working "as designed" its not "not working" if the browser cant get control of your mic, it shows you the slashed mic
* when did the browser ask to use your mic? maybe it didnt... this is why its slashed
* `Also the audio player doesn't show up unless there is an audio file already attached (which I actually like)` when does an audio player show up when there is no audio file?

**Comment by hisakonog** [comment]
* Safari never asks to use the mic. 
* when I was testing the new release in Chrome, there was always a player showing up when I expanded a datum even if there was no associated audio which was confusing. looks like it's gone now.

**Comment by cesine** [comment]
probably the player is the audio recording monitor... if you turned on audio recording then you can see it on all datum.  maybe we can hide it since they dont need to listen to themselves while recording, and the green volume meter while recording should be enough info

**Comment by hisakonog** [comment]
Yes, you are right, when the audio recording is turned on, then the player shows up and start "playing" (counting seconds). The monitor player keeps counting when you stop recording, so it is rather confusing than serving as a "monitor". I think we should hide it, the green volume meter is enough for users to know that they are recording.

**Comment by cesine** [comment]
@hisakonog  okay i created a seperate issue to hide the audio element #1850

**Comment by cesine** [comment]
![image](https://cloud.githubusercontent.com/assets/196199/7863837/970049ac-052c-11e5-90d9-bcbfa449c109.jpg)
