### ISSUE TITLE
LingSync  IE

### ISSUE THREAD

**Issue by hisakonog** [OpenSourceFieldlinguistics/FieldDB#1831]
Just as a record, app.lingsync.org does not show any contents but a blank page with Internet Explorer on Windows.

**Comment by cesine** [comment]
can you try the same test with http://app.phophlo.ca ?

**Comment by cesine** [comment]
Can you make a screenshot too so we can know which kind of internet explorer and which kind of windows

**Comment by hisakonog** [comment]
screenshot 
![lingsync on ie](https://cloud.githubusercontent.com/assets/760694/5880899/0c425582-a30a-11e4-8f53-67c7b987f9c7.PNG)

**Comment by hisakonog** [comment]
Windows 7 and IE version 9.0.34.
