### ISSUE TITLE
authdev and corpusdev need new security certificates

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#1840]
@jrwdunham to let you know, the certs on authdev and corpusdev expired on feb 3, so you will have connection problems for debugging if you are using them. it will take probably 12 more hours for our certificate signing authority to issue the new certificates.

**Comment by jrwdunham** [comment]
Thanks for letting me know. Was this Richard's problem? He wrote me saying
he was having issues accessing his corpora.

**Comment by cesine** [comment]
no, it was not richard's problem. i guess i should reply to tell him im working on it, even if he should be sleeping... #1846 

it actually days to get startssl to generate the certs, they take hours to verify each step (~4 steps) and are "down" on weekend nights (ie my day time!) grr. now they new issued certs are in place..
