### ISSUE TITLE
Test new server with appdev

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#1880]
known issues:

* cant remove someone from the corpus (need to add a new function to the api)
* cant request corpusteam when the user is part of the team, need to check the permissions and the code
{ status: 401,
  error: 'Requesting user `testmacserverfromoldserver` is not a member of the corpus team.' }
* text grids arent generated http://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

 - [x] learn x can download sample data
 - [x] load the app (http://appdev.lingsync.org)
 - [x] login
 - [ ] if browser (firefox) remembers password user can just click login
 - [x] register
 - [x] create a corpus
 - [x] rename a corpus
 - [x] edit a corpus description and view the changes in hovering over the corpus in the corpora list
 - [x] select corpus
 - [ ] select lingllama's corpus
 - [x] change to another corpus
 - [x] it should show the corpus title and current session on the black nav bar when editing data
 - [x] enter 1 datum
 - [x] delete 1 datum
 - [x] keyboard focus always goes first field in edit template (when you use teh arrows to go between datum)
 - [x] up and down arrows goes between datum and between pages once you are in a datum
 - [x] enter in a new datum brings you to the next datum, in a normal datum it does nothing
 - [x] new datum are showing on the page you are on, until you use a pagination arrow,then they fall into the chronological order they were entered
 - [x] tab takes you between fields in the data
 - [x] hover over a field tells you the teams help conventions of that field
 - [x] optional grammatical judgement shows up in front of utterance
 - [ ] ~~refresh page and see if fields for McGill template show up (Utterance, Morphemes, Gloss, Translation, IPA, Notes)~~
 - [x] use full template
 - [ ] ~~load the app uses the fulltemplate regardless of the local storage preferences~~
 - [x] use full template with user specified fields
 - [ ] ~~use mcgill template (no longer needed, corpus admins can customize the interface themselves)~~
 - [ ] ~~use yale template (no longer needed, corpus admins can customize the interface themselves)~~
 - [ ] ~~use compact template (no longer needed, corpus admins can customize the interface themselves)~~
 - [x] use pagination arrows
 - [x] save 1 or many datum
 - [x] edit 1 or many datum in the same version
 - [ ] edit 1 or many datum from a previous version
 - [ ] editing a datum should produce only one activity and only one modified by users field
 - [x] create a new session
 - [x] app selects most recent session by default
 - [x] edit a session
 - [x] delete a session
 - [x] record audio 
 - [ ] ~~record video~~ 
 - [x] upload an mp3 
 - [x] upload a wav
 - [ ] upload a mp4 (or any movie)
 - [x] add a comment
 - [x] search for something
 - [x] search for t 
 - [x] search for z 
 - [x] click on export
 - [x] the new fields (ipa and notes) are exported correctly
 - [x] export a lot of data
 - [x] enter wrong password
 - [x] enter wrong username
 - [x] change password
 - [x] reset password (incorrect passwords 5 times)
 - [x] use the forgot password button (and follow its instructions)
 - [x] try connecting to server when user is offline
 - [ ] try connecting to server when server is offline
 - [x] test glosser
 - [ ] others...

**Comment by cesine** [comment]
@hisakonog you can start testing now @jrwdunham  you can work on your screencast now

**Comment by hisakonog** [comment]
- [x] rename a corpus 
The corpus name change takes effect right away - as you edit, you see what you are editing. I like it. 

- [x] edit a corpus description and view the changes in hovering over the corpus in the corpora list 
Corpus description edit does not take effect immediately - you edit and save and go back to the corpora list but the edit is not in the hover over yet. When you log out and log in again, then you can see the edit in the hover over. 

- [x] it should show the corpus title and current session on the black nav bar when editing data 
It shows the corpus name but not the session title. In fact I don't think I've ever seen the session title there...   

- [ ] enter in a new datum brings you to the next datum, in a normal datum it does nothing 
I

**Comment by hisakonog** [comment]
- [ ] new datum are showing on the page you are on, until you use a pagination arrow,then they fall into the chronological order they were entered 
- [ ] use pagination arrows 

Can't see pagination arrows, maybe because of the "to the new server" message? 
![screen shot 2015-02-27 at 9 03 48 pm](https://cloud.githubusercontent.com/assets/760694/6424301/7fde757c-bec4-11e4-85e3-49a272cf7373.png)

**Comment by hisakonog** [comment]
- [ ] select lingllama's corpus 

Can't access lingllamma's corpus
![linglammaunaccessible](https://cloud.githubusercontent.com/assets/760694/6424310/bc6fa63c-bec4-11e4-98c6-1eac3450f131.png)

**Comment by cesine** [comment]
@hisakonog  you cant access lingllama's corpus. none of the testing users are on his team.


i've reviewed the logs to find if anyone experienced problems
* the only people working were hisako lizzie and joel
* someone in Honolulu tried to curl the commands in the ComputEL/CURL paper 67.53.48.134 - - [27/Feb/2015:16:53:13 -0500] "GET /public-curldemo/ HTTP/1.1" "401" 78 "-" "curl/7.37.1" "-"

**Comment by cesine** [comment]
@hisakonog  `Can't see pagination arrows` i modified the message so it shows only if you cant login, refresh the page and try again.

**Comment by cesine** [comment]
`enter in a new datum brings you to the next datum, in a normal datum it does nothing 
I` it works for me in my `a_fifth_corpus` which corpus did you use

**Comment by hisakonog** [comment]
nemopapa's "v2.37.05.07.35ss Testing new server" corpus

**Comment by hisakonog** [comment]
hisakonog can't access lingllama either and it only has phophlo corpus. so maybe hisakonog is also a test user?

**Comment by jrwdunham** [comment]
someone in Honolulu tried to curl the commands in the ComputEL/CURL paper 67.53.48.134 - - [27/Feb/2015:16:53:13 -0500] "GET /public-curldemo/ HTTP/1.1" "401" 78 "-" "curl/7.37.1" "-"

Whoever could that have been?

**Comment by cesine** [comment]
yeah, i saw other activity from that ip and then was dissapointed :( it was you :)


`hisakonog can't access lingllama` i tried with a user i konw has access, the problem that i didnt update both parts of the config to switch back to the prod server. should be better now

**Comment by hisakonog** [comment]
There is something strange about how data show up in the right side column. The data entered on the right-side data fields show up all stuck together. 

![somethingwrongwithrightsidefields](https://cloud.githubusercontent.com/assets/760694/6424535/f58cdc18-beca-11e4-91fa-4943a6941b3c.png)

When I changed the order of fields so that the left- and right-side columns switch, the right-side ones got stuck together. 
![screen shot 2015-02-27 at 9 49 37 pm](https://cloud.githubusercontent.com/assets/760694/6424553/8aee5584-becb-11e4-9138-508e9771e629.png)

**Comment by cesine** [comment]
thanks i'll take a look

**Comment by hisakonog** [comment]
- [ ] editing a datum should produce only one activity and only one modified by users field 

Many times but not ALL the time, just expanding a datum (i.e. clicking the expand datum icon) without editing or commenting get registered as an activity. But I can not pinpoint exactly when this happens... something to do with the timing of Save, and whether +Create New button is red or blue, it seems...

**Comment by cesine** [comment]
ahaha i just created an issue for that, fixed it and deployed it #1883

**Comment by hisakonog** [comment]
yup i saw it.

**Comment by hisakonog** [comment]
Create New Session: why does it say "cancel" where "Edit Session" says "Goal"? 

![whycancel](https://cloud.githubusercontent.com/assets/760694/6424671/90b8aca8-bed0-11e4-998e-e861876104c6.png)

**Comment by cesine** [comment]
@hisakonog  any more things to add, or shall we declare this as finished as it will be?

**Comment by hisakonog** [comment]
I think we can close this. closing.
