### ISSUE TITLE
new server is often non-responsive

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#1904]

**Comment by hisakonog** [comment]
MONSTATIC alert 

**Corpus** 

|   | Alert | OK | recovery time | 
| --- | --- | --- | --- |
| Feb 27 | 17:22:13 |   |   |
| Mar 2 | 08: 27:12 | 09:00:23 | 30 min |  
| Mar 2 | 18:38:24 | 19:42:20 | 1 h | 
| Mar 3 | 08:12:08 | 08:12:16 | 8 sec | 
| Mar 4 | 10:37:09 | 16:32:31 | 6 h | 
| Mar 4 | 17:05:04 | 20:18:44 | 3 h | 

**Speechdev**

|   | Alert | OK | recovery time | 
| --- | --- | --- | --- | 
| Mar 2 | 03:02:15 | 03:34:29 | 30 min | 
| Mar 2 | 18:36:03 | 19:39:38 | 1 h |
| Mar 3 | 08:12:09 | 08:12:16 | 7 sec | 
| Mar 4 | 10:37:09 | 16:32:31 | 6 h | 
| Mar 4 | 17:05:07 |   |   |

**Comment by cesine** [comment]
We are still having trouble with the new machine being non-responsive. 

We didn't have this problem with our previous server, but our previous server was an Ubuntu machine.  I suspect  there is something about the mac's config we don't know that is causing it to sleep or overload or something.

Do you have any guides for setting up the mac so that it stays responsive? We found a guide but it requires using remote desktop, and I don't know how to do that via the terminal, or if the mac we sent you already had remote desktop enabled. http://www.macminicolo.net/ebooks/InitialSetupEbook.pdf


Is asking you to enable it for us one of the things you can do in the remote hands service ticket? 



For reference, here is the downtime we've had recently. 
We cant find a pattern, so we are guessing its the mac's config, not anything to do with mac stadium. do you have a page where we can check on the macstadium ping time or something?


https://github.com/OpenSourceFieldlinguistics/FieldDB/issues/1904

MONSTATIC alert

Corpus

Alert	OK	recovery time
Feb 27	17:22:13		
Mar 2	08: 27:12	09:00:23	30 min
Mar 2	18:38:24	19:42:20	1 h
Mar 3	08:12:08	08:12:16	8 sec
Mar 4	10:37:09	16:32:31	6 h
Mar 4	17:05:04	20:18:44	3 h
Speechdev

Alert	OK	recovery time
Mar 2	03:02:15	03:34:29	30 min
Mar 2	18:36:03	19:39:38	1 h
Mar 3	08:12:09	08:12:16	7 sec
Mar 4	10:37:09	16:32:31	6 h
Mar 4	17:05:07

**Comment by cesine** [comment]
Have you set the "put the computer to sleep when it is inactive for" to never?

**Comment by cesine** [comment]
Thanks! 

I found a page that explains how to do this via ssh, it was set to 10minutes! 
http://osxdaily.com/2015/02/03/set-or-disable-sleep-due-to-mac-system-inactivity-from-the-command-line-in-os-x/

```
$ sudo systemsetup -getcomputersleep
Password:
Computer Sleep: after 10 minutes

$ sudo systemsetup -setcomputersleep Never
setcomputersleep: Never

$ sudo systemsetup -getcomputersleep
Computer Sleep: Never
```

i think this is the problem, thanks so much! closing...
