### ISSUE TITLE
post slides/videos etc from ICLDC

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#1905]
@jrwdunham can you post stuff on facebook :)

**Comment by cesine** [comment]
some notes 

- our agreements about intellectual property ownership need to be more explicit
  - maybe they are explicit, but I'm just ignorant of something
  - we talk about how corpus creators can license their corpora and make them
    public, but we're not explicit about who owns the data on our LingSync
    web service. (At least not to my knowledge.)
  - at any rate, more clairy on this point would be good

**Comment by cesine** [comment]
We tried to be extra clear about this on website https://www.lingsync.org/privacy.html and the details of how users should manage their corpora and sharing their corpus in the [CAML paper](https://github.com/OpenSourceFieldlinguistics/FieldDB/blob/master/docs/CAML/caml2012.pdf?raw=true)

Here is a copy:

Your data is your data.
In the spirit of transparency we provide you with these templates of standard social web app privacy policies and terms of service to fully explain the data involved in LingSync.org. There are two types:

* data which is typical data that most social websites use to make sure their app is user friendly and to let users trust each other and collaborate, and
data which is your fieldlinguistics data (your "Corpus")
* In both cases, we don't use your private data, and we have no partnerships with third parties. In fact, we try to avoid collecting any sensitive private data about you. We would also be happy to give you your private data, just request it.

However : we are a team of Open Source volunteers, as such we have no legal team, no customer support team and we want you to know that LingSync.org and the software that runs on it is provided AS IS, WITH NO WARENTEE, NO FORMAL SUPPORT AND NO GUARENTEE THAT IT WILL OR WILL NOT DO ANYTHING. If you are worried about these things, we prefer that you set up your own private server so that we don't have to worry about the legal implications of hosting your data.

**Comment by jrwdunham** [comment]
Ok, I'll do this once I'm at home and have power and time to let my computer sit while YouTube does its video conversion stuff.

**Comment by jrwdunham** [comment]
Done. See:

- https://www.facebook.com/LingSyncApp
- https://youtu.be/c2dCboStB3k
