### ISSUE TITLE
guarantees of institutional support?

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#1907]
- one question was about whether we have guarantees of institutional support
  into the future, which is something people want when they consider using a
  piece of software
  - I couldn't make guarantees, and I guess we can't really either, beyond:
    - it's open source
    - I'll be working on it as long as I hold this postdoc 
    - I would like to continue supporting the project, assuming I can get a job
      that makes this possible...

**Comment by cesine** [comment]
This is a hard question. 

Answer # 1

Maybe the question becomes easier to understand if we document how much time and resources the project requires. We engineered the project and choose our technologies so that they would require minimal resources.

* Server: cheep server with 4GB of RAM and 2TB raided disk, and unlimited bandwidth is enough. It costs us 300$ a year, the cost of 1 coffee a day :) We can pay that out of pocket because we have day jobs... 
* Primary GUI: 1 day a week, roughly 4 days a month
* Infrastructure: 1 day a month

Total cost of guaranteeing the project will exist for the next 10 YEARS:
* $300x10 =  $3,000
* 5X12X10 = 600 days  / 3,650 days

That's dirt cheep, no grant needed... 

Answer # 2

We do have institutional support, both in the traditional and non-traditional sense. We probably have the best collaborative institutional support I've ever heard about.
* 8 Universities who use the app and who told us they have IT budgets which they can use to help pay for infrastructure (which we haven't it used yet because our infrastructure is too cheep, its easier to just pay it with one of the grants we already have)
* 4 Grants thus far totalling over $1,000,000 CAD (I think, I never asked the exact amount) which rely on the app, and have funded the students who built/test the apps
* 2 other universities, not part of the initial partnership, who funded their students to work on the app
* 1 profitable Software Start-up who funnels money from their paying clients to pay for postdocs :p and 1 day a week of open source development/mentoring so that their developers don't get bored working for paying clients.
* Over 90% of the code which manages our infrastructure maintained by the the largest open source foundation in the world, Apache Foundation (couchdb) and a software company specializing in high performance cloud infrastructure Joyent (nodejs), thats efficient re-use of resources. We are pretty good at not re-inventing the wheel.

We actually do have institutional support both in the non-traditional sense, and in the traditional theoretical linguistic app sense, the institutions were just slow to admit that they are using the app until the app is well known, and more people cite us as a technical role model, then they come out of the closet after the feedback you got at the IDLC :) You could ask them if they are ready... You could make a slide for your slides deck that shows 

Answer # 3

When the interns were researching whether they should start this project or not, they found that most institutional projects die. Grants get cut, departments change, people move around and change research focus. The only institution who hasn't come and gone is the SIL. They contacted Gretchen very early on when the project was just beginning to find out how we can reuse their code and resources and not create overlap :)

**Comment by cesine** [comment]
<div class="section-content"><script>
$(document).ready(function () {
  $('.platinum').each(function() {
    randomImage = $('.platinum').get(Math.floor(Math.random()*10) % $('.platinum').length);
    randomImage.parentNode.insertBefore(this, randomImage);
  });
});
</script>

<p>The Apache Software Foundation could not exist without the continued
generous support from the community. We would like to take this opportunity
to thank our Sponsors. If you are interested in sponsoring the ASF, please
read our <a href="/foundation/sponsorship.html">sponsorship page</a>.</p>
<h1 id="platinum-sponsors">Platinum Sponsor(s)</h1>
<p>The Apache Software Foundation would like to thank the following Platinum
Sponsor(s):</p>

<p class="platinum"><img alt="Facebook logo" src="http://www.apache.org/foundation/images/fb-logo.png" title="Facebook logo"><br>
<a href="http://www.facebook.com/">Facebook</a>.</p><p class="platinum"><img alt="Microsoft logo" src="http://www.apache.org/foundation/images/microsoft.jpg" title="Microsoft logo"><br>
<a href="http://www.microsoft.com/">Microsoft</a>.</p>
<p class="platinum"><img alt="Cloudera logo" src="http://www.apache.org/foundation/images/cloudera-platinum.png" title="Cloudera logo"><br> 
<a href="http://www.cloudera.com/">Cloudera</a>.</p><p class="platinum"><img alt="Google logo" src="http://www.apache.org/foundation/images/google.jpg" title="Google logo"><br>
<a href="http://www.google.com/">Google</a>.</p>

<p class="platinum"><img alt="Citrix logo" src="http://www.apache.org/foundation/images/citrix.png" title="Citrix logo"><br>
<a href="http://www.citrix.com/">Citrix</a>.</p>
<p class="platinum"><img src="http://www.apache.org/foundation/images/matt-mullenweg.jpg" alt="Matt Mullenweg" title="Matt Mullenweg" width="250"><br>
<a href="http://ma.tt/">Matt Mullenweg</a>.</p><p class="platinum"><img alt="Yahoo logo" src="http://www.apache.org/foundation/images/yahoo.jpg" title="Yahoo logo"><br>
<a href="http://www.yahoo.com/">Yahoo!</a>.</p>

<h1 id="gold-sponsors">Gold Sponsor(s)</h1>
<p>The Apache Software Foundation would like to thank the following Gold
Sponsor(s):</p>
<p><img alt="Comcast logo" src="http://www.apache.org/foundation/images/comcast.jpg" title="Comcast logo"> 
<a href="http://www.comcast.com/">Comcast</a>.</p>
<p><img alt="HP logo" src="http://www.apache.org/foundation/images/hp.png" title="HP logo"> 
<a href="http://opensource.hp.com/">HP</a>.</p>
<p><img alt="Hortonworks logo" src="http://www.apache.org/foundation/images/hortonworks.png" title="Hortonworks logo"> 
<a href="http://www.hortonworks.com/">Hortonworks</a>.</p>
<p><img alt="IBM logo" src="http://www.apache.org/foundation/images/ibm.png" title="IBM logo"> 
<a href="http://www.ibm.com/">IBM</a>.</p>
<h1 id="silver-sponsors">Silver Sponsor(s)</h1>
<p>The Apache Software Foundation would like to thank the following Silver
Sponsor(s):</p>
<p><img alt="Budget Direct logo" src="http://www.apache.org/foundation/images/budget-direct-120.png" title="Budget Direct logo"> 
<a href="http://www.budgetdirect.com.au/">Budget Direct</a>.</p>
<p><img alt="Cerner logo" src="http://www.apache.org/foundation/images/cerner.png" title="Cerner logo">
<a href="http://engineering.cerner.com">Cerner</a>.</p>
<p><img alt="Serenata Flowers logo" src="http://www.apache.org/foundation/images/serenataflowers-silver.png" title="Serenata Flowers logo"> 
<a href="http://www.serenataflowers.com/">Serenata Flowers</a>.</p>
<p><img alt="InMotion Hosting logo" src="http://www.apache.org/foundation/images/inmotion-hosting.png" title="InMotion Hosting logo">
<a href="http://www.inmotionhosting.com/">InMotion Hosting</a>.</p>
<p><img alt="iSIGMA logo" src="http://www.apache.org/foundation/images/isigma.png" title="iSIGMA logo">
<a href="http://www.isigma.net">iSIGMA</a>.</p>
<p><img alt="Pivotal logo" src="http://www.apache.org/foundation/images/pivotal.png" title="Pivotal logo"> 
<a href="http://www.gopivotal.com/">Pivotal</a>.</p>
<p><img alt="Produban logo" src="http://www.apache.org/foundation/images/produban.png" title="Produban logo"> 
<a href="http://www.produban.com/">Produban</a>.</p>
<p><img alt="WANDISCO logo" src="http://www.apache.org/foundation/images/wandisco.png" title="WANDISCO logo"> 
<a href="http://www.wandisco.com/">WANDISCO</a>.</p>
<h1 id="bronze-sponsors">Bronze Sponsor(s)</h1>
<p>The Apache Software Foundation would like to thank the following Bronze
Sponsor(s):</p>
<p><a href="http://www.accor.com/" rel="nofollow">Accor</a>.</p>

<p>
</p><p><a href="http://www.basistechnology.com/" rel="nofollow">Basis Technology</a>.</p> 
<p><a href="http://www.bluehost.com/opensource/" rel="nofollow">Bluehost</a>.</p> 
<p><a href="http://www.cloudsoftcorp.com/" rel="nofollow">Cloudsoft Corporation</a>.</p>
<p><a href="http://www.samsung.com/" rel="nofollow">Samsung</a>.</p>
<p><a href="http://www.talend.com/" rel="nofollow">Talend</a>.</p>
<p><a href="http://www.twitter.com/" rel="nofollow">Twitter</a>.</p><p></p>
<h1 id="infrastructure-support">Infrastructure support</h1>
<p>The Apache Software Foundation would like to thank the following
organizations for providing infrastructure support:</p>
<p><img alt="OSUOSL logo" src="http://www.apache.org/foundation/images/osl.jpg" title="OSUOSL logo">
<img alt="Surfnet Logo" src="http://www.apache.org/foundation/images/surfnet_logo.gif" title="surfnet logo">
<img alt="FUB Logo" src="http://www.apache.org/foundation/images/FUB_Logo_Web_RGB_96x27.gif" title="FUB logo"></p>
<p>Server hosting and bandwidth provided by <a href="http://www.osuosl.org/">Oregon State University Open
Source Lab (OSUOSL)</a> (USA),
<a href="http://www.surfnet.nl/">SURFnet</a> and <a href="http://www.fu-berlin.de/en/">FUB</a>(EU).</p>
<p><img alt="PingMyBox logo" src="http://www.apache.org/foundation/images/pingmybox.png" title="PingMyBox logo">
<img alt="PagerDuty logo" src="http://www.apache.org/foundation/images/pagerduty.png" title="PagerDuty logo"></p>
<p>Monitoring and alert services provided by: 
<a href="https://pingmybox.com">PingMyBox</a> and <a href="https://pagerduty.com">PagerDuty</a></p>
<p><img alt="Symantec CodeSigning logo" src="http://www.apache.org/foundation/images/symanteccs.jpg" title="Symantec CodeSigning logo"></p>
<p>Codesigning services: 
<a href="http://www.symantec.com/code-signing/secure-app-service">Symantec</a></p>
<p>Secondary DNS Services:</p>
<p><img alt="no-ip.com logo" src="http://www.apache.org/foundation/images/no-ip.gif" title="no-ip.com logo"></p>
<p>Secondary DNS provided by <a href="http://no-ip.com">No-IP Managed DNS</a> ,</p>
<p>Donation of servers: HP</p>
<p>Donation of virtualization software: VMWare.</p>
<p>Donation of wildcard SSL certificates: <a href="https://www.thawte.com/">Thawte</a>.</p>
<h1 id="individual-donations">Individual Donations</h1>
<p>The Apache Software Foundation receives many smaller donations from 
individuals via our PayPal and Amazon Payments services (details 
<a href="http://www.apache.org/foundation/contributing.html">here</a>).</p>
<p>We would like to thank all of our individual donations for their 
support of our work, and for their willingness to contribute with
only this as recognition for their generosity.</p>
<h1 id="awards">Awards</h1>
<p>The Apache Software Foundation would like to gratefully thank the following
organizations and the community at large for acknowledging the success of
the Apache Software Foundation and its projects:</p>
<ul>
<li>Association of Computing Machinery - Software System Award</li>
</ul></div>

**Comment by cesine** [comment]
@HughP  it seems like this question also came from you, do you consider this question as answered? if yes i think you now have enough powers to close it yourself ?

**Comment by HughP** [comment]
@cesine I actually don't have permissions to Close this issue, not sure why... I have never been sponsored by Apache Foundation, so I have a general question: does AF stipulate that you need to advertise their donors? Otherwise I would generally, I think naming direct sponsors is clearer and sufficient.

**Comment by cesine** [comment]
it looks like github wont let collaborators manage issues :( only people with push access. 

sounds good, we already name the direct sponsors in the acknowledgements of the slides and on the people page :) https://www.lingsync.org/#/people
