### ISSUE TITLE
User added notification is confusing 

### ISSUE THREAD

**Issue by hisakonog** [OpenSourceFieldlinguistics/FieldDB#1908]
This is a bit nitpicky thing but I make an issue anyway. When I add a new user to a corpus, the app gives a message: 
"User [username] now has [permission types] access to [corpus name], the user **was** already a member of this corpus team." (emphasis by me) 
I found this message confusing, especially the past tense "was". It indicates as if the newly added user used to be a member of the corpus but somehow lost her access and you are now recovering her access. (That's actually what I thought had happened, but it turned out that the user I added had registered to LingSync only 1/2 hour before I added her.) 
Could we either remove the second clause of the message or change "was" to "is"?

**Comment by cesine** [comment]
is this the line? i think it already says "is"

https://github.com/OpenSourceFieldlinguistics/AuthenticationWebService/blob/master/lib/userauthentication.js#L1035

**Comment by cesine** [comment]
ah i found it in the refactor branch (not merged yet). can you edit it? 
here is a link to the editable version of that file. 

https://github.com/cesine/AuthenticationWebService/edit/refactor/lib/userauthentication.js#L1318

**Comment by hisakonog** [comment]
I proposed a change in the refactor branch.

**Comment by cesine** [comment]
i just added myself to a corpus where i wasnt a user, and it told me "the user was already a member "
