### ISSUE TITLE
spreadsheet is painfully slow

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#1914]
P.S. On an unrelated note, you might want to add some sort of ""jump to page"" feature. Returning to page 23 of a 53 page data set after reloading the page was a slow and frustrating experience. "

**Comment by cesine** [comment]
The difference between the version my class has been using and the chrome extension version would explain why the class has been so frustrated with lingsync in general. I don't think the class is aware of the extenion.

**Comment by hisakonog** [comment]
@cesine Do you think the server hardware is responsible for the slowness? Should we consider switching back to Linux (the current hosting subscription ends in Feb)?

**Comment by cesine** [comment]
Yes we will definitely change back to Linux :(
