### ISSUE TITLE
Some datum are missing the session saved in  appVersion: "2.45.02.01.33ss Mon Mar 2 01:37:08 EST 2015"

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#1916]
```javascript 
percentComplete 100
2Datum.js:245 Uncaught TypeError: Cannot read property 'datumFields' of undefinedBackbone.Model.extend.parse @ Datum.js:245Backbone.Model @ backbone.js:254Model @ backbone-couchdb.js:351child @ backbone.js:1566_.extend._prepareModel @ backbone.js:915_.extend.set @ backbone.js:706_.extend.fetch.options.success @ backbone.js:865Backbone.couch_connector.con.read_collection._opts.success @ backbone-couchdb.js:182$.ajax.$.extend.$.extend.complete @ jquery.couch.js:1029jQuery.Callbacks.fire @ jquery.js:2863jQuery.Callbacks.self.fireWith @ jquery.js:2975done @ jquery.js:7344jQuery.ajaxTransport.send.callback @ jquery.js:7751
fielddb.js:116 percentComplete 100
Datum.js:245 Uncaught TypeError: Cannot read property 'datumFields' of undefined

```

![screen shot 2015-03-20 at 12 59 05 am](https://cloud.githubusercontent.com/assets/196199/6737171/94122dc6-ce9c-11e4-8e39-b16d6357c79f.png)

**Comment by cesine** [comment]
@hisakonog  @jrwdunham  it looks like these datum were created during a version of the app that has only been deployed at appdev.

so which one of you naughties made a testing corpus in the lingllama user :) or do we have someone else using appdev who knows how to login as lingllama (there is no button for this in the spreadhsheet, you have to literaly type his username and password to login as him)

**Comment by hisakonog** [comment]
I did delete a session from lingllama's corpus -- it was an empty session mistakenly created in the lingllama corpus by one of ConU students. I don't remember the date I did it. Could that be the culprit? 
Are people able to make sessions inside lingllama corpus?

**Comment by cesine** [comment]
Nope, thats not related. any user can create and edit sessions datumin lingllama's corpus, thats why we made it. it hasnt been a problem thus far, i often look at the activity feed because its the frist thing you see when you log out of the prototype so i can see if anyone has been naughty.

this is a more interesting thing where someone logged in as lingllama, not from their own account, and created a  clearly funny corpus called "fiddelsticks" using the appdev version of the app ;) its not really a problem, i removed lingllama from admin and writer so whoever made the corpus can still read it. its really nota problem, we have the permissions to manage these things. i just thought it might be one of you given the corpus' name :) and its uniqly developer like genesis

**Comment by hisakonog** [comment]
@cesine, if a user (not lingllama) create a session in lingllama's corpus, would other users see it too, as it is a public corpus... ?

**Comment by cesine** [comment]
yes, this is the point. many users (who are not in a class) have no opportunity to see activity of other users, this is why we have a grafitti corpus
