### ISSUE TITLE
Contact Mark about his Big Data in Linguistics course

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#1920]
http://www.ling.upenn.edu/courses/ling052/

LING052
Freshman Seminar: Big Data in Linguistics
Spring 2014

Instructor: Mark Liberman

Time:	MW 3:00-4:30
Place:	Fishbowl Seminar Room, Institute for Research in Cognitive Science, 3401 Walnut St., Suite 400A
Course description:	Big, fast, cheap, computers; ubiquitous digital networks and data streams; huge and growing digital archives; good and improving algorithms for automatic analysis of text and speech: All of this creates a cornucopia of research opportunities for practical applications from politics to marketing and finance, and for fundamental research in areas from medicine and literary analysis to linguistics. 

This course will survey the history and prospects of "Big Data" research involving speech, text, and communication, through a combination of readings and class projects. Programming ability is not required, though interested participants will have an opportunity to apply any computational skills that they have or wish to develop.

See the overview for the general plan of the course; and the schedule for details and links to lecture notes, outside readings and other assignments.

---

@jrwdunham  did you see this? Can you write to Mark to find out if he wants to collaborate next time he has this course, if there is a hands on component or if it makes sense to collaborate in some way. 

This is essentially why we built the app, so that linguistics students could learn how to script their data manipulation, and also see it in a user friendly way too :) Louisa's spider can pull down parallel text data in low resource languages which can be imported and then the students can run their algorithms on the data and get first hand experience on making infinite loops, and n^2 run times instead of n Log(n) or other lovely intractable piplines :) and we could have more data centered students using the project

**Comment by jrwdunham** [comment]
Yes, this course sounds great. I would like to take it! I think I'll see how Mark responds to my initial email to him, before bringing up possible collaboration ...

**Comment by cesine** [comment]
sounds like a plan, i figured you'd like the course :)
