### ISSUE TITLE
UCB feature request: categorizable texts

### ISSUE THREAD

**Issue by jrwdunham** [OpenSourceFieldlinguistics/FieldDB#1939]
The ability to categorize texts. For example, to categorize a text's genre as song. This could be accomplished via conventionalized tags on text (FieldDB data list, OLD collection) objects; e.g., "genre:song"

**Comment by cesine** [comment]
maybe you should show them this:

1. add the field for genre, order it as you wish
![screen shot 2015-04-09 at 5 07 48 pm](https://cloud.githubusercontent.com/assets/196199/7064682/fc192368-deda-11e4-94d5-ee591629054b.png)


2. use the field for genre
![screen shot 2015-04-09 at 5 06 03 pm](https://cloud.githubusercontent.com/assets/196199/7064669/cd98ef14-deda-11e4-92ab-d34783edb044.png)

**Comment by jrwdunham** [comment]
Yes, but this is tagging the genre on the datum/form level. It doesn't quite make sense since (presumably) that single phrase is not a song. First we need the text/subcorpus more formally recognized in the data structure and then we need to be able to tag those by genre.

**Comment by cesine** [comment]
sorry, the same fields apply at the elicitation session level. i should have made screnshots for that instead. the spreadsheet assumes you dont care about your session metadata, so there is no interface for it there, but there is in the prototype.

I found a screenshot in #1705

![screen shot 2014-10-30 at 4 07 43 pm](https://cloud.githubusercontent.com/assets/196199/4851188/6f06e908-6070-11e4-96d8-72bfc86e072d.png)

Text/subcorpora (either as the source of the data, or as an ordered list of data for another purpose) ARE a very important part of the data structure, its not part of the spreadsheet app to make the app very simple for field methods classes. they aren't as important as in the OLD but that's something you can improve :) the choice of the word "session" to represent the source of data (elicitation session, transcript, radio show, tv show, conversation, publication etc) was a bad word choice. oops. it doesn't mean it doesn't exist in the data structure.
