### ISSUE TITLE
someone registered username 'idontcare'

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#1965]
@jrwdunham  or @hisakonog we deactivated the user 'idontcare' since they probably don't care... :) (incase this was you guys, or you know who this person was...)

**Comment by cesine** [comment]
@jrwdunham @hisakonog here is the compt rendu from monitoring the logs yesterday to make sure the server stayed responsive and we noted any issues which came up.

6 out of 11 new users came from the PIs themselves! probably they made these users to practice adding users, or to practice for their workshop, or to test to see if new corpora look like jessica requested. either way, we should check with the m to ask if we can delete these users...
* jessica55  (to be deleted?)
* harvardtest  (its coming from a New Hampshire IP 24.61.9.222 where alan was. (to be deleted?)
* alan1 (to be deleted?) same ip as harvardtest 24.61.9.222
* alan2 (to be deleted?)
* alan3 (to be deleted?)
* jessica1 (to be deleted?)

1 user who had trouble registering:
* lena15 (no email)
* karvovsk (a real user, probably same person, two minutes later)
* lenka (a real user, with email created because karvovsk's creation failed, which I saw and fixed ~ 30 min later)

4 real users, one of which didn't care....
* syjl86  (a real user)
* yhe (no email)
* ava (a real user)
* bradl (a real user)



Other suspicious activity:

* yolo420forever This user has no email, and doesn't exist on other websites. their username according ot the urban dictionary means "you-only-live-once-smoke-canabis-forever"  They registered from 137.54.24.248 physically inside the University Of Virginia 
* idontcare This user has no email, and their username says it all... They registered from 137.54.24.248 physically inside the University Of Virginia, probably friends with Mr. you-only-live-once-smoke-canabis-forever

Both of these users violate the terms of use section 4.4 but we can leave them alone for a week or so to see if they continue using the app. (they were trying to collaborate together, and choose silly usernames probably for testing it out...).

**Comment by jrwdunham** [comment]
Hey,

Alan was helping people register and he thought he saw a pattern where
users with "k" in their name couldn't register. I'm skeptical about this,
but I thought I'd just mention it.

- J

**Comment by cesine** [comment]
haha cute ;)
its not the k, it was that the server timed out, now it will try twice.

I figured he knew about this user because he wasn't able to add them to the corpus, this is why I wanted to make sure you guys knew that this was an exception which was fixed both for that user and in the code.
