### ISSUE TITLE
non-operational in-browser audio recording

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#1973]

**Comment by hisakonog** [comment]
The app is not recording... speech.lingsync.org is normal (```cannot get```) and the internal mic works (tested with praat) and the app seems to behave like it's recording and uploads the file, but sound is not registered. The volume indicator does not show in the record button. 
![screen shot 2015-05-15 at 17 20 26](https://cloud.githubusercontent.com/assets/760694/7662126/d58bc332-fb26-11e4-9ef6-2c64fe94f590.png)

**Comment by cesine** [comment]
This is what the app looks like if it cant contact the server

![screen shot 2015-05-19 at 12 12 05 am](https://cloud.githubusercontent.com/assets/196199/7695306/bccc3b3c-fdbb-11e4-9f27-db5c09b152c3.png)

**Comment by cesine** [comment]
the problem was a typo in the commonjs lib dc6ec5228b52376a5e8ff2c4d2acee41a8803c0e
