### ISSUE TITLE
Test release 3.4

### ISSUE THREAD

**Issue by hisakonog** [OpenSourceFieldlinguistics/FieldDB#1987]
~~v3.4.19.21.53ss~~
v3.5.27.23.44ss (May 28) 

 - [ ] learn x can download sample data
 - [x] load the app (http://appdev.lingsync.org)
 - [x] login
 - [ ] if browser (firefox) remembers password user can just click login
 - [x] register
 - [x] create a corpus
 - [ ] rename a corpus
 - [ ] edit a corpus description and view the changes in hovering over the corpus in the corpora list
 - [x] select corpus
 - [ ] ~~select lingllama's corpus~~
 - [x] change to another corpus
 - [ ] select a session 
 - [x] data entry page nav bar has all the menu items and buttons there need to be 
 - [x] it should show the corpus title and current session on the black nav bar when editing data
 - [x] enter 1 datum
 - [x] delete 1 datum
 - [x] up and down arrows goes between datum and between pages once you are in a datum
 - [x] keyboard focus always goes first field in edit template (when you use the arrows to go between datum)
 - [x] enter in a new datum brings you to the next datum, in a normal datum it does nothing
 - [x] use pagination arrows
 - [x] new datum are showing on the page you are on, until you use a pagination arrow,then they fall into the chronological order they were entered
 - [x] tab takes you between fields in the data
 - [x] hover over a field tells you the teams help conventions of that field
 - [x] optional grammatical judgement shows up in front of utterance
 - [x] add a new field 
 - [x] use full template with user specified fields
 - [x] save 1 or many datum
 - [x] edit 1 or many datum created in the current version
 - [x] edit 1 or many datum created in a previous version
 - [ ] editing a datum should produce only one activity and only one modified by users field
 - [ ] app selects most recent session by default
 - [x] create a new session 
 - [ ] change sessions 
 - [x] edit a session
 - [x] delete a session 
 - [ ] record audio 
 - [ ] ~~record video~~ 
 - [ ] upload an mp3 
 - [ ] upload a wav
 - [ ] upload a mp4 (or any movie)
 - [x] add a comment
 - [x] search for something
 - [ ] "Clear results" clears search results and shows all the datums in the session you are in
 - [x] search for t 
 - [x] search for z 
 - [x] click on export
 - [x] the new (user defined) fields are exported correctly
 - [x] export a lot of data
 - [x] enter wrong password
 - [x] enter wrong username
 - [x] change password
 - [x] reset password (incorrect passwords 5 times)
 - [x] use the forgot password button (and follow its instructions)
 - [ ] try connecting to server when user is offline
 - [ ] try connecting to server when server is offline
 - [x] test glosser
 - [x] remove someone from a corpus 
 - [x] add someone to a corpus 
 - [ ] others...

**Comment by hisakonog** [comment]
- [x] register 

Registering works fine, however, after the newly registered user logged in, selected the Practice corpus and chose Practice session, the data entry page showed up empty like this: 
![screen shot 2015-05-25 at 2 17 50 pm](https://cloud.githubusercontent.com/assets/760694/7800783/dee3e440-02e8-11e5-90aa-02ae0655ab81.png)

The console log: 
![screen shot 2015-05-25 at 2 20 38 pm](https://cloud.githubusercontent.com/assets/760694/7800813/4c1ce1a6-02e9-11e5-9cb7-11d35a0124d5.png)

After refresh page, the normal data entry page shows up.

**Comment by hisakonog** [comment]
- [x] create a corpus 

(I'm using the newly created user) Creating a new corpus via corpus setting (enter corpus title in the text box and click "create", not changing the descriptions) gives you the normal popup message 
However, when you select the newly created corpus, the first you see is this: 
![screen shot 2015-05-25 at 3 13 24 pm](https://cloud.githubusercontent.com/assets/760694/7801318/eb614c82-02f0-11e5-88c0-8f527720ca5c.png)

Partial console log (it says "created new corpus"): 
![screen shot 2015-05-25 at 3 17 33 pm](https://cloud.githubusercontent.com/assets/760694/7801358/7240f978-02f1-11e5-8f16-ad98ce119088.png)

Again you need to refresh page in order to have the normal data entry view with fields.

**Comment by hisakonog** [comment]
- [ ] rename a corpus
 - [ ] edit a corpus description and view the changes in hovering over the corpus in the corpora list

When I rename a corpus and changed its description yesterday, the edits got reflected in the corpora list right away. However, logged out and after 20+ hours, the edits got disappeared from the corpora list (both the name and the description). 
 
![screen shot 2015-05-26 at 1 07 27 pm](https://cloud.githubusercontent.com/assets/760694/7818401/82059252-03a9-11e5-83a7-cb9fa5bc8356.png)

Does this mean that the edits were stored in the local storage but didn't get saved to the server, or something?

**Comment by hisakonog** [comment]
- [ ] data entry page correctly shows up with default data fields

Also see the comments on Register and Create Corpus above. Refresh page resolves this. 

![screen shot 2015-05-26 at 1 08 28 pm](https://cloud.githubusercontent.com/assets/760694/7818781/b319242e-03ab-11e5-9cc4-282e6f6f2931.png)

It seems/feels like this happens when 
a) you open a new corpus for the first time 
b) you open an already existing corpus but your previous login was hours ago 

Will keep taking notes when it happens

**Comment by hisakonog** [comment]
- [ ] it should show the corpus title and current session on the black nav bar when editing data 

When you go from the corpora list: 
![screen shot 2015-05-26 at 1 56 30 pm](https://cloud.githubusercontent.com/assets/760694/7819384/6d5f9aea-03af-11e5-9839-6680f56cdda2.png)

Then refresh page: 
![screen shot 2015-05-26 at 1 58 03 pm](https://cloud.githubusercontent.com/assets/760694/7819431/c0d31a58-03af-11e5-899d-3b0a8aee5751.png)

Maybe there is an extra path/step to load a page that causes this (and data entry not showing up)?

**Comment by hisakonog** [comment]
- [x] enter 1 datum
 - [x] delete 1 datum

was able to delete a datum too, but where did the "Save/Saved/Saving" button go? 
![screen shot 2015-05-26 at 2 11 54 pm](https://cloud.githubusercontent.com/assets/760694/7819736/b758dc36-03b1-11e5-8669-d7a6e83f40dd.png)

**Comment by hisakonog** [comment]
@cesine, the appdev says it's not saving data. I got this: 

![screen shot 2015-05-26 at 2 26 33 pm](https://cloud.githubusercontent.com/assets/760694/7820080/04312368-03b4-11e5-86f4-4dde84f62e23.png)

I can not go to the Session mode, nor log out, I get the popup "Please save changes before continuing". 

I reloaded the page (despite the warning popup) and it logged me out. When I re-logged in, chose the corpus and the session, and refreshed page (because it didn't show the data entry page right away, see the comments above), the data were there. 

I did use appdev yesterday to test recording and uploading audio. I did so in one of the existing corpora (2.45.0666ss TEST under nemotest1). It looked like the appdev saved the uploaded audio files, but when I looked at it right now using both app and appdev versions, the uploaded files weren't there. So I guess the appdev wasn't actually saving. Although the attempted recorded file is there (it didn't register sound).

**Comment by hisakonog** [comment]
Okay my comments are getting messier... 
When I logged in as nemotest1, the appdev does have Save button and Search mode in the nav bar. 

![screen shot 2015-05-26 at 2 50 05 pm](https://cloud.githubusercontent.com/assets/760694/7820465/9742837a-03b6-11e5-86dd-f50ef5098d5d.png)

The only difference is that, this user and the corpus were made in the previous release version (I think 2.45).  The user and corpus missing the Save button and Search mode are made in the current appdev (3.4).

**Comment by hisakonog** [comment]
- [ ] up and down arrows goes between datum and between pages once you are in a datum
 - [ ] keyboard focus always goes first field in edit template (when you use the arrows to go between datum)

Up and down arrows do not go between datums. The up arrow goes to the top of the string entered within a currently focused field, the down arrow to the end. 

When you click a datum, the focus is always on the first field.

**Comment by hisakonog** [comment]
- [ ] use pagination arrows
 - [ ] new datum are showing on the page you are on, until you use a pagination arrow,then they fall into the chronological order they were entered

There is no pagination arrows in this version...

**Comment by hisakonog** [comment]
- [x] add a new field 

Added a new field "Second Translation". The data entry page show the field with this name, but the list of fields on the Corpus settings page does not reflect the name. 

![screen shot 2015-05-27 at 3 45 33 pm](https://cloud.githubusercontent.com/assets/760694/7845917/31bbebfe-0488-11e5-85c9-47ff64678913.png)

**Comment by hisakonog** [comment]
- [ ] The field specification on the data entry page matches that in the Templates in Corpus Setting

The right bottom field on the data entry page is "Discussion" Why is it "documentation" in the Template? 

![screen shot 2015-05-27 at 4 05 27 pm](https://cloud.githubusercontent.com/assets/760694/7846365/14206072-048b-11e5-8d96-bc0a56999386.png)

![screen shot 2015-05-27 at 4 05 48 pm](https://cloud.githubusercontent.com/assets/760694/7846385/22123d40-048b-11e5-969b-9f43b119a156.png)


(Incidentally, I think we should change Templates to Template)

**Comment by hisakonog** [comment]
- [ ] add a new field 

Once you add one new field, you can not add another field without leaving the app. Unless you logout and re-login, the "Add a field" button does not respond. 

After adding a new field, changing the field order, saving the changes and making sure the newly added field is in the right place in the data entry mode, I refreshed the Corpus setting page to see if refreshing page helps to recover the response of the "Add a field" button.  I not only lost the newly added field, but also lost menus in the nav bar... 

![screen shot 2015-05-28 at 2 11 21 pm](https://cloud.githubusercontent.com/assets/760694/7867580/ee67b7a8-0544-11e5-9a7d-3f7344dc2c18.png)

![screen shot 2015-05-28 at 2 13 20 pm](https://cloud.githubusercontent.com/assets/760694/7867587/f627e10c-0544-11e5-9233-e56a0bee2d91.png)

![screen shot 2015-05-28 at 2 14 24 pm](https://cloud.githubusercontent.com/assets/760694/7867630/2f50fe64-0545-11e5-8031-6a86bb0f7640.png)

![screen shot 2015-05-28 at 2 26 11 pm](https://cloud.githubusercontent.com/assets/760694/7867722/b9f2c0a2-0545-11e5-9c88-7c7831174a0c.png)

![screen shot 2015-05-28 at 2 14 42 pm](https://cloud.githubusercontent.com/assets/760694/7867631/31e34768-0545-11e5-8161-d15d7724362b.png)

I tried refreshing the data entry page after adding a new field, which too caused losing of the newly added field. 

![screen shot 2015-05-28 at 2 42 05 pm](https://cloud.githubusercontent.com/assets/760694/7868154/194de052-0548-11e5-8874-00e24962c056.png)

![screen shot 2015-05-28 at 2 43 03 pm](https://cloud.githubusercontent.com/assets/760694/7868156/1efee8a2-0548-11e5-8e20-b3c91ff517e9.png)

**Comment by hisakonog** [comment]
- [ ] upload an mp3 
- [ ] upload a wav 

Neither .mp3 nor .wav was uploaded. 
![screen shot 2015-05-28 at 2 58 55 pm](https://cloud.githubusercontent.com/assets/760694/7876646/32d36a38-059d-11e5-95a4-326220646c67.png)

**Comment by hisakonog** [comment]
- [ ] record audio 

Audio recording itself is working, it registers sound and I can listen to them. However, it seems to have a problem uploading/saving the recorded file. 

![screen shot 2015-05-29 at 1 00 47 am](https://cloud.githubusercontent.com/assets/760694/7876737/8a7a1312-059e-11e5-8781-b017dc86ef6f.png)

**Comment by hisakonog** [comment]
- [ ] change sessions 

Changing between sessions in the Session mode works fine. I can switch between sessions. 
But changing sessions from the "Corpus loaded" page always ends up on a same "default" session (e.g. it's Negation session in Malayalam corpus; it's nemotest2 practice session in テストコーパス)

**Comment by hisakonog** [comment]
- [x] create a new session 

Creating a session works both in the Session mode and from the "Corpus loaded" page.

**Comment by hisakonog** [comment]
- [x] delete a session 

Deleting a session works fine, and I like that it asks the reason to delete. 

When you delete a session, the screen turns to "view all sessions". If you go click the LingSync logo and go to "Corpus loaded" page immediately, the session defaults into "view all sessions" (i.e. whichever session you choose in the session list, you will see all sessions).  Maybe this has something to do with "app selects most recent session by default"? And the app recognizes only the session selected via the Session mode and defaults in to it as the most recent one?

**Comment by hisakonog** [comment]
- [x] add someone to a corpus 
 - [ ] remove someone from a corpus 

When nemotest2 was the only user of テストコーパス, there was no gravatar under user types. When I added nemotest1 as admin to nemotest2's テストコーパス, I saw two gravatars show up. Then I added nemo33 as read/write, the "Ok" button in the popup ("nemo33 has reader writer access to...") did not respond a while (maybe a minute or two?) and when that popup/modal finally disappeared, I didn't see the 3rd gravatar for nemo33. I refreshed the page and all gravatars were gone. I logged out and re-logged in, there was no gravatar. (And since there is no gravatar, I can't remove a user...) 
![screen shot 2015-05-29 at 12 35 08 pm](https://cloud.githubusercontent.com/assets/760694/7887654/bad043bc-0600-11e5-8cd7-fb150fe0d1cc.png)

The users were surely added, both nemotest1 and nemo33 have nemotest2's "undefined" corpus in their corpora lists. 

(Incidentally, nemotest2's テストコーパス keeps appearing as "undefined", it may be because when I created it and was testing on it, the app happened to get updated, I think...)

**Comment by hisakonog** [comment]
- [ ] editing a datum should produce only one activity and only one modified by users field 

(I think this is the bug whose fix we need to wait till Dative is in...?) 
Editing a datum produces one activity and one modified by user (i.e. one disk icon with date and time, one gravatar). But NOT editing a datum also produces activity and modified by user: expanding/shrinking a datum, moving between fields in a datum (without modifying the data) causes the date/time to update and adds an extra gravatar. In previous versions, it seemed to happen when the app was auto-saving (or when the save button was red?), but in this version (3.5.27.23.44) it seems to happen whenever (and it causes the save button to turn red if it wasn't already).

**Comment by hisakonog** [comment]
- [x] add a comment 

Adding comment works. There is a delete button and when you click it, it shows the popup asking "are you sure to remove comment?" but it doesn't delete. Are we planning to actually delete comments?

**Comment by hisakonog** [comment]
- [ ] search something 

Search itself is working, but "Clear results" does not clear the results. In the previous versions, "Clear results" gave back all the datums in the session you were in. But in the current version, it keeps showing only the search results, and search keeps narrowing down. When you go back to data entry by hitting the menu, it still keeps showing only the search results. You need to refresh page to get all the datums back.

**Comment by hisakonog** [comment]
- [x] search for t 
- [x] search for z 

search for t and z per se is working fine.  But I found that Search searches comments too. I am not sure if it is a good idea... 
![screen shot 2015-05-29 at 2 59 39 pm](https://cloud.githubusercontent.com/assets/760694/7890477/45c3078a-0614-11e5-87ed-d7771f0fa63e.png)

Speaking of which, you said 
*searching for 5 will get all datum in made in 2015. i think this is okay...* 
But in some languages (like Bantu family) certain classes of morphemes are annotated with numbers. So if I want morphemes of the class 5 and search hits all datums made in 2015, that would be really annoying...

**Comment by hisakonog** [comment]
Other things: 
* Data field customization on the corpus setting page: 
  * It shows two titles and two help texts, one for non-linguists and the other for linguists. And there is a button "Easy/Advanced mode. Is the button supposed to toggle between the two (linguists/non-linguists)? 
  * Also, I don't like some titles and help texts for non-linguists (e.g. "English" for "Translation"?) There is an issue on this (also Joel's commit), so I'll chime in on the relevant issue.

**Comment by cesine** [comment]
Tonights todos in this round of fixes:

* test swith between two users and see corpsu stuff
* list of corpora titles should show (max 3 hours)
* use "Glossser" and first ten characters
* search for any source of logout
* add a new field
* Templates
* data entry shoud show on settings page
* hide the two fields,  and show the linguist ones since those are the ones joel worked on and they work for linguists and not for non-linguists
* audio popup, cant attach
* changing sessions on corpus list
* delete comment doesnt remove comments
* clear search is not showing all the data, and keeps restricting search
* try a regex search

**Comment by cesine** [comment]
@hisakonog i released the above fixes (all except the corpus list matching the corpus title) as v 3.6.01.23.36ss in appdev please test as soon as humanly possible so we can decide if its ready to go out to everybody

**Comment by hisakonog** [comment]
**Testing above fixes in release v3.6.01.23.36ss**

 - [ ] use "Glossser" and first ten characters

Sometimes the buttons and corpus/session names stay like this (some other times they re-align themselves after a few seconds)
![screen shot 2015-06-02 at 8 16 24 am](https://cloud.githubusercontent.com/assets/760694/7935553/dab5b250-08ff-11e5-9ead-0b29e31230bf.png)

The session shows the date it was created rather than the title. I think maybe it's better to show the title? 

(also, just to note: I think there was a quirk instance. I switched users to nemo814 and went to spreadsheettesting_migmaq, and I think (although not 100% sure) I didn't need to refresh page to see the data. However, I didn't have the "Save" button, until I refreshed the page) 
![screen shot 2015-06-02 at 7 48 39 am](https://cloud.githubusercontent.com/assets/760694/7935608/39ef80ac-0900-11e5-8507-51d12095c802.png)

**Comment by hisakonog** [comment]
- [x] add a new field 
- [x] Templates > Templates  
- [ ] hide the two fields,  and show the linguist ones since those are the ones joel worked on and they work for linguists and not for non-linguists 

The help texts are showing the version before Joel's edits, and the hover-overs are huge.

**Comment by hisakonog** [comment]
- [x] data entry should show on settings page if the data has been loaded, otherwise you have to go to the corpus page :) 

Setting page showing Data Entry, Session, FAQ, Glosser. I think this makes sense.

**Comment by hisakonog** [comment]
- [x] changing sessions on corpus list 

Yes :)  changing session works in both the full-screen session mode and the corpus list. However... in the small-screen session mode, session dropdown is unresponsive.

**Comment by hisakonog** [comment]
- [x] delete comment doesn't remove comments 

Comments now delete :)

**Comment by hisakonog** [comment]
- [ ] audio popup, cant attach 

When you record audio to the app, it records and uploads and the "save" button turns red to warn the user to save. And it saves. 
When you attach audio files, the player shows up and plays the file. However the "save" button doesn't turn red, and the file is not saved (you go to another corpus and come back, the attached file isn't there) even if you click the green "Saved" button.

**Comment by hisakonog** [comment]
- [x] clear search is not showing all the data, and keeps restricting search
 - [x] try a regex search, i tried this one which correctly eliminated "five"

**Comment by hisakonog** [comment]
- loading corpus template 

My テストコーパス has the following fields: Transcription, Morphemes, Gloss, AddField1, Translation, Second Translation
![screen shot 2015-06-02 at 9 46 14 am](https://cloud.githubusercontent.com/assets/760694/7937432/eb671482-090d-11e5-8000-5af4890f047d.png)

My セミオートGlosser Testing corpus has the following fields: Transcription, Morphemes, Gloss, Translation, Context, Discussion 
![screen shot 2015-06-02 at 10 05 50 am](https://cloud.githubusercontent.com/assets/760694/7937650/5d26ec22-090f-11e5-9f26-a1a1600cb93c.png)

When I switch between the two corpora, the template gets carried over from the corpus I was in to the corpus I switch to, e.g. I was in セミオートGlosser Testing and switch to テストコーパス, the template for セミオートGlosser Testing corpus stays until I reload the page. 

![screen shot 2015-06-02 at 9 49 32 am](https://cloud.githubusercontent.com/assets/760694/7937718/be00ef8e-090f-11e5-848f-3cdb3d537253.png)

**Comment by cesine** [comment]
@hisakonog the two things we talkeda bout this morning (newcorpus and import file) are fixed and released as 3.6.01.01.57ss on appdev

**Comment by hisakonog** [comment]
Thanks @cesine new corpus has the new help text, and audio record/upload are both working.

**Comment by hisakonog** [comment]
- [x] remove someone from a role (admin, writer, reader, commenter) in a corpus  
- [ ] Read-only user should have Read-only view when they open the corpus 

nemotest2 removed nemotest1 from Admin and Writer roles, but nemotest1 still has Reader permission.  nemotest1 logged in and he had the data entry write/edit view. Entered a datum and clicked save, then got this (I think this popup is scary...): 
![screen shot 2015-06-02 at 3 06 19 pm](https://cloud.githubusercontent.com/assets/760694/7944627/d8c824fc-0939-11e5-92ec-1ab2a1e70673.png)

Clicked "OK" then the screen is like this: 
![screen shot 2015-06-02 at 3 07 26 pm](https://cloud.githubusercontent.com/assets/760694/7944660/151ad1e8-093a-11e5-9b37-344183092760.png)

The pink "Saving" keeps blinking. Logging out gives "Please save changes before you continue!" so I reload the page. Then nemotest1 has Read-only view. 
When nemotest1 logged out and re-logged in immediately, he had Read-only view. However, when I switched to another user and came back to nemotest1, he again had Write/Edit view.

**Comment by hisakonog** [comment]
I think this might also be related to "switch between users and see corpus stuff". 

After logging out as nemotest1, I logged in as nemotest2 and went to corpus setting to remove the nemotest1 completely, but  the app told me nemotest2 doesn't have the admin access. The i refreshed the page and got back the corpus setting page.

**Comment by hisakonog** [comment]
Incidentally, Refreshing team and removing someone seems to take quite a bit of time (30~60sec) during which the screen is unresponsive (can't click nor scroll).

**Comment by cesine** [comment]
released as v 3.6.1.23.49ss on appdev

**Comment by hisakonog** [comment]
~~v3.4.19.21.53ss~~
~~v3.5.27.23.44ss (May 28)~~ 
v3.6.1.23.49ss (June 3) 

 - [ ] learn x can download sample data
 - [ ] load the app (http://appdev.lingsync.org)
 - [ ] login
 - [ ] if browser (firefox) remembers password user can just click login
 - [ ] register
 - [ ] create a corpus
 - [ ] rename a corpus
 - [ ] edit a corpus description and view the changes in hovering over the corpus in the corpora list
 - [ ] select corpus
 - [ ] ~~select lingllama's corpus~~
 - [ ] change to another corpus
 - [ ] select a session 
 - [ ] data entry page nav bar has all the menu items and buttons there need to be 
 - [ ] it should show the corpus title and current session on the black nav bar when editing data
 - [ ] enter 1 datum
 - [ ] delete 1 datum
 - [ ] up and down arrows goes between datum and between pages once you are in a datum
 - [ ] keyboard focus always goes first field in edit template (when you use the arrows to go between datum)
 - [ ] enter in a new datum brings you to the next datum, in a normal datum it does nothing
 - [ ] use pagination arrows
 - [ ] new datum are showing on the page you are on, until you use a pagination arrow,then they fall into the chronological order they were entered
 - [ ] tab takes you between fields in the data
 - [ ] hover over a field tells you the teams help conventions of that field
 - [ ] optional grammatical judgement shows up in front of utterance
 - [ ] add a new field 
 - [ ] use full template with user specified fields
 - [ ] save 1 or many datum
 - [ ] edit 1 or many datum created in the current version
 - [ ] edit 1 or many datum created in a previous version
 - [ ] editing a datum should produce only one activity and only one modified by users field
 - [ ] app selects most recent session by default
 - [ ] create a new session 
 - [ ] change sessions in Session mode 
 - [ ] change sessions on Corpus list  
 - [ ] edit a session
 - [ ] delete a session 
 - [ ] record audio 
 - [ ] ~~record video~~ 
 - [ ] upload an mp3 
 - [ ] upload a wav
 - [ ] upload a mp4 (or any movie)
 - [ ] add a comment 
 - [ ] delete a comment 
 - [ ] search for something
 - [ ] "Clear results" clears search results and shows all the datums in the session you are in 
 - [ ] use regex in search query 
 - [ ] search for t 
 - [ ] search for z 
 - [ ] click on export
 - [ ] the new (user defined) fields are exported correctly
 - [ ] export a lot of data
 - [ ] enter wrong password
 - [ ] enter wrong username
 - [ ] change password
 - [ ] reset password (incorrect passwords 5 times)
 - [ ] use the forgot password button (and follow its instructions)
 - [ ] try connecting to server when user is offline
 - [ ] try connecting to server when server is offline
 - [ ] test glosser
 - [ ] add someone to a corpus 
 - [ ] remove someone from a corpus 
 - [ ] others...

**Comment by hisakonog** [comment]
Just discovered something interesting... If you have a datum open, and keep hitting tab, it takes you between the fields and after the last field, it steps on Add Comment > Record > Choose file > Drag and drop text field > Delete. I think this is okay...

**Comment by hisakonog** [comment]
- [ ] edit a corpus description and view the changes in hovering over the corpus in the corpora list 

This should be its own issue. I am ignoring it for this test round.

**Comment by hisakonog** [comment]
- [ ] Read-only user (with no admin, writer, commenter role) should see Read-only view 

You add a new Read-only user (call him X) to a corpus (call the corpus Y). 
When X **first** opens the corpus Y, X has Edit view. In order for X to have Read-only view, X needs to refresh page: 
![screen shot 2015-06-03 at 11 40 46 am](https://cloud.githubusercontent.com/assets/760694/7964727/53c0f334-09e7-11e5-9624-f4aea8bd6cc9.png)
 
![screen shot 2015-06-03 at 11 41 37 am](https://cloud.githubusercontent.com/assets/760694/7964889/2a9a7876-09e8-11e5-8ba1-f466425a2980.png)

![screen shot 2015-06-03 at 11 41 57 am](https://cloud.githubusercontent.com/assets/760694/7964895/3112f692-09e8-11e5-95d2-70603d7a2c73.png)

![screen shot 2015-06-03 at 11 42 54 am](https://cloud.githubusercontent.com/assets/760694/7964901/367909e6-09e8-11e5-9381-1ee581b3d626.png)

Once X reloads the page and gets Read-only view, his subsequent login to the corpus Y has always Read-only view.

**Comment by hisakonog** [comment]
- [ ] removing someone from admin should not give them editable corpus setting page view 

A user removed from admin permission could still have the editable view of the corpus setting page. Although they can not add another user (they get "You don't have permission to perform this action"), they can still edit the corpus name and description. They need to reload the page to not have access to editable view. 

![screen shot 2015-06-03 at 12 27 43 pm](https://cloud.githubusercontent.com/assets/760694/7965826/038365f8-09ee-11e5-8130-4bca48e7c72f.png)

![screen shot 2015-06-03 at 12 32 22 pm](https://cloud.githubusercontent.com/assets/760694/7965839/13552638-09ee-11e5-9b32-1a7c03bb05c0.png)

![screen shot 2015-06-03 at 12 36 01 pm](https://cloud.githubusercontent.com/assets/760694/7965850/1e7836b8-09ee-11e5-9a50-be4769d5478e.png)

**Comment by hisakonog** [comment]
- [x] add a new field
 - [ ] use full template with user specified fields
 - [ ] changing corpus loads the template specified to that corpus 

These work provided that a user is in the same login session.  In short, newly added fields are saved but rearranging the field order seems to get lost when you logout. 

![screen shot 2015-06-03 at 2 25 01 pm](https://cloud.githubusercontent.com/assets/760694/7970560/ef6a32d0-0a0c-11e5-86e8-224213e8b1b2.png) 

![screen shot 2015-06-03 at 2 28 32 pm](https://cloud.githubusercontent.com/assets/760694/7970565/f64e88d0-0a0c-11e5-9687-56d4ccd6b988.png) 

![screen shot 2015-06-03 at 2 30 41 pm](https://cloud.githubusercontent.com/assets/760694/7970581/133f240e-0a0d-11e5-91ba-2a112b99f57b.png)

![screen shot 2015-06-03 at 2 32 52 pm](https://cloud.githubusercontent.com/assets/760694/7970614/4683a1a0-0a0d-11e5-9696-549142e40afb.png) 

![screen shot 2015-06-03 at 2 37 43 pm](https://cloud.githubusercontent.com/assets/760694/7970620/528d19b8-0a0d-11e5-8b56-20ae9b601fb5.png)

![screen shot 2015-06-03 at 2 40 00 pm](https://cloud.githubusercontent.com/assets/760694/7970657/942d8218-0a0d-11e5-81ca-05ee3634baa1.png)


Next I tried whether reloading the corpus list page before doing anything with the corpus setting would make a difference. Conclusion, it didn't. 

![screen shot 2015-06-03 at 2 44 15 pm](https://cloud.githubusercontent.com/assets/760694/7970665/9f506110-0a0d-11e5-840f-de68e9467009.png) 

![screen shot 2015-06-03 at 2 46 17 pm](https://cloud.githubusercontent.com/assets/760694/7970676/aa44749e-0a0d-11e5-9d14-5703efc75715.png)

I logged out, re-logged in and reloaded the corpus list page to make sure the corpus name/label is showing (as opposed to the pouchname). Then went to Data Entry and got this. 

![screen shot 2015-06-03 at 2 51 34 pm](https://cloud.githubusercontent.com/assets/760694/7970801/788501ac-0a0e-11e5-861f-a2118bfc2025.png)

Below the console when the corpus setting is saving and is saved. It looks like it's saved correctly (I moved 4th Translation after Translation, i.e. it's 5th field).  

![screen shot 2015-06-03 at 4 08 52 pm](https://cloud.githubusercontent.com/assets/760694/7970966/9252cd70-0a0f-11e5-8074-354dfe585500.png)  

![screen shot 2015-06-03 at 4 16 42 pm](https://cloud.githubusercontent.com/assets/760694/7970972/9c820a18-0a0f-11e5-8eab-f88acab16d73.png)

**Comment by hisakonog** [comment]
- [x] edit 1 or many datum created in the current version
 - [ ] edit 1 or many datum created in a previous version 

Editing datum created in the current version (you edit some field and push Tab) triggers Save button to turn Red, and creates an activity. 

**Editing datum created May 27 and prior** 
You edit some field in the Right column then push Tab, it triggers Save button to turn Red and creates an activity. 
You edit some field in the **Left** column then push Tab, it neither triggers Red Save button nor creates an activity (below another lengthy series of screenshots documenting the discovery process of this bug)

![screen shot 2015-06-03 at 10 13 12 pm](https://cloud.githubusercontent.com/assets/760694/7975893/bc29f600-0a41-11e5-9933-c2be758fa7d0.png)

![screen shot 2015-06-03 at 10 16 36 pm](https://cloud.githubusercontent.com/assets/760694/7975899/c2caafd6-0a41-11e5-979b-71ec3f7ee48d.png)

![screen shot 2015-06-03 at 10 17 42 pm](https://cloud.githubusercontent.com/assets/760694/7975956/b1b43522-0a42-11e5-9c2e-1530b0a87da9.png)

![screen shot 2015-06-03 at 10 37 50 pm](https://cloud.githubusercontent.com/assets/760694/7975976/f7abb6c2-0a42-11e5-9651-740843f75dc7.png)

![screen shot 2015-06-03 at 10 38 33 pm](https://cloud.githubusercontent.com/assets/760694/7975996/3ad72292-0a43-11e5-8225-3202663eab2e.png)


**May 27 and prior datums** Once you got to save edits (or register an activity like comments) in the current version, then edit start working normally, i.e. whatever field you edit and push tab, Red Save button is triggered.

**Comment by hisakonog** [comment]
- [x] "Clear results" clears search results and shows all the datums in the session you are in

Clearing results sometimes takes a bit longer, but it works.

**Comment by hisakonog** [comment]
- [x] the new (user defined) fields are exported correctly 

It exports correctly provided that you successfully saved the user defined fields in the template and do not lose it. See 3 comments above.

**Comment by hisakonog** [comment]
- [ ] add someone to a corpus 

- Read-only: Added in the team, have access to the granted corpus, but no notification email received. 
- Write-only (in fact Write/Comment): Added in the team, received notification email, but do NOT have access to the corpus (corpus not listed in their corpus list, reloading the corpus list page has no effect) 
- Write/Read(/Comment): Added in the team, received notification and have access to the corpus. 
- Admin/Write/Read/Comment: Added in the team, received notification and have access to the corpus. 

![screen shot 2015-06-04 at 10 19 44 am](https://cloud.githubusercontent.com/assets/760694/7987580/63a672e0-0aac-11e5-9e78-e5d8f5d3da35.png)

![screen shot 2015-06-04 at 11 07 59 am](https://cloud.githubusercontent.com/assets/760694/7987584/6766d8c0-0aac-11e5-80c3-09eca7936d36.png)

**Comment by hisakonog** [comment]
- [ ] Admin users consistently have editable corpus setting page 

Related to 
 - [ ] removing someone from admin should not give them editable corpus setting page view 
 - [ ] Read-only user (with no admin, writer, commenter role) should see Read-only view 


Switching between Admin and non-Admin users causes Admin users to not see editable corpus setting page. 

 - Admin<sub>1</sub> > Admin<sub>2</sub> : Admin<sub>2</sub> has editable corpus setting view
 - Admin > non-Admin : non-Admin has editable corpus setting view until he reloads page
 - non-Admin > Admin : Admin is told he has no Admin permission until he reloads page 

Note on Reloading page: It does not have to be the corpus setting page. Users can reload any of the Corpus list, Data Entry and Corpus Setting pages and they will have the right view for their permissions.

**Comment by cesine** [comment]
* permissions are wierd when page is loaded
* saving 2 times in a row on a corpus doesnt work correctly

**Comment by cesine** [comment]
replaced previous version lingsyncspreadsheet_v2.45.02.01.33ss Mon Mar 2 01:37:08 EST 2015

with version  v3.6.1.23.49ss (from june 2) on jul 31
