### ISSUE TITLE
Libra Office Histogram Tutorial

### ISSUE THREAD

**Issue by vronvali** [OpenSourceFieldlinguistics/FieldDB#2006]

**Comment by vronvali** [comment]
http://ajhaupt.blogspot.com/2012/01/how-to-create-histogram-in-openoffice.html

Shows how to create a basic histogram in open office.

**Comment by vronvali** [comment]
https://sites.google.com/site/calcfunctions/calc-help-articles/creating-a-histogram

Shows how to create the histogram and how to modify the design features.

**Comment by cesine** [comment]
This didnt teach you how to automatically detect intervals in your data. Next time you have a similar data set we can try to find a LibreOffice interval tutorial.
