### ISSUE TITLE
How to use Yeoman to scaffold apps and modules

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#2010]
Now that you have finished the #38  code academy training in javascript, you know a bit about the vocab and syntax of javascript. now you should learn a bit about the socio-linguistics of javascript, and fortunately there is a tool that can build architecture for which follows best practices.

Complete this tutorial, and push the result to your github.
http://yeoman.io/codelab.html

After you have completed this tutorial you can turn on Travis (instructions in #2011)

**Comment by vronvali** [comment]
Error that occurred in step 8

```
PhantomJS 1.9.8 (Mac OS X 0.0.0) Controller: MainCtrl should have no items to start FAILED
	TypeError: 'undefined' is not a function (evaluating 'expect(scope.todos.length).toBE(0)')
	    at /Users/veronica/mytodo/test/spec/controllers/main.js:20
```

**Comment by vronvali** [comment]
Hi Louisa, you can do this while you wait for Gina. She might be late.

**Comment by louisa-bielig** [comment]
Here is my result for the todo app:

https://github.com/louisa-bielig/mytodo
