### ISSUE TITLE
How to use Travis to automatically run tests when you push to GitHub

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#2011]
Do the sample first:
http://docs.travis-ci.com/user/for-beginners/#To-get-started-with-Travis-CI%3A

Then turn it on for your project you built in #2010 (yeoman scaffolds  a working .travis.yml for you)
http://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A

**Comment by vronvali** [comment]
After much trial and error I think that we are still missing a key ingredient to get the Travis CI to work with angular.

**Comment by cesine** [comment]
k no problem i can take a look later
