### ISSUE TITLE
Set up a windows computer

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#2013]
@louisa-bielig  leave a link here for all the things you installed

* https://windows.github.com/
* https://nodejs.org/
* http://www.sublimetext.com/3
* http://ffmpeg.zeranoe.com/builds/
* http://couchdb.apache.org/

http://www.srware.net/en/

**Comment by cesine** [comment]
Use this script to find what you need to install 

https://github.com/OpenSourceFieldlinguistics/FieldDB/blob/master/install_mac_download_and_set_up_fielddb_servers_for_new_developers_quick_start.sh

**Comment by louisa-bielig** [comment]
Create a FIELDDB_HOME Environment variable 

http://www.computerhope.com/issues/ch000549.htm

**Comment by louisa-bielig** [comment]
notes 
https://wiki.apache.org/couchdb/Quirks_on_Windows
http://superuser.com/questions/42537/is-there-any-sudo-command-for-windows
