### ISSUE TITLE
Cant use localhost couchdb https on windows

### ISSUE THREAD

**Issue by louisa-bielig** [OpenSourceFieldlinguistics/FieldDB#2015]
![cannot access https](https://cloud.githubusercontent.com/assets/4334000/8087452/43aa740c-0f9b-11e5-80db-4a91e93a3e45.PNG)

**Comment by cesine** [comment]
Not much we can do about this. We tried converting the couchdb proxy into https but ran out of time. 

For now, we managed to use the http couchdb on windows since we were working with the lexicon browser (not a chrome app).
