### ISSUE TITLE
Take a look project's google analytics

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#2020]
@vronvali  using what you learned in #2002 , please take a look at the projects's analytics and take some screenshots of graphs/dashboards/queries which you create while exploring the data, and maybe a sentence discussing what you find interesting int he project. send your screenshots to @hisakonog by email, if there are graphs that you guys think users might want to find out about, you can post some of the screenshots on the project's facebook. (you can join the facebook group btw https://www.facebook.com/LingSyncApp )

**Comment by vronvali** [comment]
Before I can successfully look at the graphs and come to conclusions about our analytics I need more background on the app.

**Comment by cesine** [comment]
here is the project website

http://lingsync.org

you can watch the videos in this play list to see what the app is, who it is for etc

https://www.youtube.com/watch?v=4XrO8AhGNqo&list=PLUrH6CNxFDrMtraL8hTLbLsQwdw1117FT
