### ISSUE TITLE
update Concordia server to Yosemite

### ISSUE THREAD

**Issue by hisakonog** [OpenSourceFieldlinguistics/FieldDB#2021]
done. @cesine please update xcode

**Comment by cesine** [comment]
@jrwdunham do you want to try you hand at configuring a server? the concordia server is ready to have the script run there is a private config repo which has all the setup for launch deamons and nginx that you will want to use if so.

**Comment by jrwdunham** [comment]
@cesine is there a deadline on this?

**Comment by cesine** [comment]
No it can wait until you want to use the server ;) (ie you could use it for nels if you need a server for both the old and lingsync)

**Comment by jrwdunham** [comment]
Hey, I'm interested in playing with this now.

Can you elaborate on "the concordia server is ready to have the script run there is a private config repo which has all the setup for launch deamons and nginx that you will want to use if so."? What/where is this "private config repo"?
