### ISSUE TITLE
Use the yo gulp-angular to build the todos tutorial instead

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#2022]
in #2010  you learned how to use Yeoman to build the scaffold for your apps, but unfortunatly the tutorial is based on an older generator which uses Grunt, and which is most often broken rather than working. 

This issue is to use the new Yeoman gulp-angular generator, and then add your existing todo code into the new project.

https://github.com/Swiip/generator-gulp-angular

You will notice that the Gulp scaffolding is different from the one you did in #2010, the gulp scaffolding actually follows angular recommendations for modularity and so it is a good experience to find your previous code, and move it into the position it should go. You will find that the gulp project has similar functionality for build, and test, but runs much faster and consumes less battery than the project you made in #2010

place screenshots here of your "before" from #2010 and "After" #2022 architecture as they look in sublime

**Comment by vronvali** [comment]
Before 
![app js](https://cloud.githubusercontent.com/assets/12688769/8257236/2fb91d00-167a-11e5-8fd1-d7f1a94a59f5.png)
![main js](https://cloud.githubusercontent.com/assets/12688769/8257238/2fc1cf4a-167a-11e5-96de-ff5e4a0406b8.png)
![main html](https://cloud.githubusercontent.com/assets/12688769/8257237/2fc1a862-167a-11e5-8fc6-6753e8d953ba.png)

**Comment by cesine** [comment]
After
![screen shot 2015-06-21 at 11 03 21 am](https://cloud.githubusercontent.com/assets/196199/8272118/2df2216a-1805-11e5-9a73-4ca0afc4f056.png)
