### ISSUE TITLE
How to load templates in angular directive specs/tests

### ISSUE THREAD

**Issue by vronvali** [OpenSourceFieldlinguistics/FieldDB#2036]
Error: Unexpected request: GET components/tutorial/tutorial.htmlNo more request expected

http://stackoverflow.com/questions/15214760/unit-testing-angularjs-directive-with-templateurl

https://github.com/meanjs/mean/issues/198

**Comment by cesine** [comment]
the problem was the path https://github.com/vronvali/tutorific/commit/7fe86d0949190591aecc9584dbb781e5fe2c0303
